using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CV.Management.Generation.Word
{
    public enum MetadataTexts
    {
        CV_TITLE,
        CV_NOTICE_FIRST,
        CV_NOTICE_SECOND,
        CV_NOTICE_THIRD,
        CV_PERSONAL,
        CV_NAME_SURNAME,
        CV_ADDRESS,
        CV_MOBILE,
        CV_EMAIL,
        CV_OTHER_INFORMATION,
        CV_LINKEDIN_LINK,
        CV_EDUCATION,
        CV_ADDITIONAL_COURSES,
        CV_DAY,
        CV_DAYS,
        CV_LANGUAGE,
        CV_LANGUAGE_SPOKEN,
        CV_LANGUAGE_WRITTEN,
        CV_LANGUAGE_PROFICIENCY,
        CV_LANGUAGE_PROFICIENCY_LEVEL,
        CV_LANGUAGE_PROFICIENCY_BASIC,
        CV_LANGUAGE_PROFICIENCY_SATISFACTORY,
        CV_LANGUAGE_PROFICIENCY_GOOD,
        CV_LANGUAGE_PROFICIENCY_EXCELLENT,
        CV_LANGUAGE_PROFICIENCY_NATIVE,
        CV_CAREER_SUMMARY,
        CV_COMPANY_INFORMATION,
        CV_COMPANY_CITY,
        CV_COMPANY_PARENT_COMPANY,
        CV_COMPANY_INDUSTRY,
        CV_COMPANY_SERVICES,
        CV_COMPANY_TURNOVER,
        CV_COMPANY_EMPLOYEES,
        CV_TASK_INFORMATION,
        CV_POSITION_REPORTING_TO,
        CV_POSTION_SUBORDINATES,
        CV_POSITION_ACHIEVEMENTS,
        CV_POSITION_REASON_FOR_LEAVING,
        CV_PRESENT,
        CV_SOCIAL_ACTIVITIES,
        CV_COMPENSATION,
        CV_COMPENSATION_CURRENT_SALARY,
        CV_COMPENSATION_CURRENT_BONUSES,
        CV_COMPENSATION_REQUESTED_SALARY,
        CV_COMPENSATION_REQUESTED_BONUSES,
        CV_COMPENSATION_ADDITIONAL_BONUSES,
        CV_TRANSITION_TIME,
        CV_NOTICE_PERIOD,
        CV_ADDITIONAL_COMMENTS
    }
}
