// <auto-generated />
namespace CV.Management.Web.MigrationsApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SkypeToOther : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkypeToOther));
        
        string IMigrationMetadata.Id
        {
            get { return "201905192039136_SkypeToOther"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
