// <auto-generated />
namespace CV.Management.Web.MigrationsApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SplitTimeInMonth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplitTimeInMonth));
        
        string IMigrationMetadata.Id
        {
            get { return "201907061550210_SplitTimeInMonth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
