// <auto-generated />
namespace CV.Management.Web.MigrationsApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AchievementsSeparate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AchievementsSeparate));
        
        string IMigrationMetadata.Id
        {
            get { return "202012040559022_AchievementsSeparate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
