//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Management.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Management.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept our privacy policy to register.
        /// </summary>
        public static string AcceptPrivacyPolicyError {
            get {
                return ResourceManager.GetString("AcceptPrivacyPolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add company.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add course.
        /// </summary>
        public static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add education.
        /// </summary>
        public static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional bonuses (company car, stock options, etc.).
        /// </summary>
        public static string AdditionalBonuses {
            get {
                return ResourceManager.GetString("AdditionalBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string AdditionalComments {
            get {
                return ResourceManager.GetString("AdditionalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string AdditionalCommentsPlaceholder {
            get {
                return ResourceManager.GetString("AdditionalCommentsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional files (certificates, motivation letter, etc.).
        /// </summary>
        public static string AdditionalFiles {
            get {
                return ResourceManager.GetString("AdditionalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add membership.
        /// </summary>
        public static string AddMembership {
            get {
                return ResourceManager.GetString("AddMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add position.
        /// </summary>
        public static string AddPosition {
            get {
                return ResourceManager.GetString("AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City, country.
        /// </summary>
        public static string AddressPlaceholder {
            get {
                return ResourceManager.GetString("AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested bonuses.
        /// </summary>
        public static string BonusRequest {
            get {
                return ResourceManager.GetString("BonusRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By registering you accept our.
        /// </summary>
        public static string ByRegistering {
            get {
                return ResourceManager.GetString("ByRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career summary.
        /// </summary>
        public static string CareerSummary {
            get {
                return ResourceManager.GetString("CareerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City, country.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name *.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation.
        /// </summary>
        public static string Compensation {
            get {
                return ResourceManager.GetString("Compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name, certificate obtained.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bonuses (gross).
        /// </summary>
        public static string CurrentBonuses {
            get {
                return ResourceManager.GetString("CurrentBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current fixed salary (gross per month, currency).
        /// </summary>
        public static string CurrentSalary {
            get {
                return ResourceManager.GetString("CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality, degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete picture.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct and indirect subordinates (numbers and functions, if you have no, leave blank).
        /// </summary>
        public static string DirectSubordinates {
            get {
                return ResourceManager.GetString("DirectSubordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education &amp; qualifications.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education entry.
        /// </summary>
        public static string EducationEntry {
            get {
                return ResourceManager.GetString("EducationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (YYYY) *.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (YYYY or MM.YYYY) *.
        /// </summary>
        public static string FromTimeWithMonth {
            get {
                return ResourceManager.GetString("FromTimeWithMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period from (YYYY).
        /// </summary>
        public static string FromYear {
            get {
                return ResourceManager.GetString("FromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name *.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry / business area.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of institution / country.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid year!.
        /// </summary>
        public static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid year and/or month!.
        /// </summary>
        public static string InvalidYearWithMonth {
            get {
                return ResourceManager.GetString("InvalidYearWithMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key tasks and responsibilities (write each in new line).
        /// </summary>
        public static string KeyTasks {
            get {
                return ResourceManager.GetString("KeyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Tasks and responsibilities (Please write each in new line);\n •Task no 1;\n •Responsibility no 2;\n •Task no 3;\n •Etc..
        /// </summary>
        public static string KeyTasksPlaceholder {
            get {
                return ResourceManager.GetString("KeyTasksPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language entry.
        /// </summary>
        public static string LanguageEntry {
            get {
                return ResourceManager.GetString("LanguageEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn link.
        /// </summary>
        public static string LinkedInLink {
            get {
                return ResourceManager.GetString("LinkedInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main products / services.
        /// </summary>
        public static string MainProductions {
            get {
                return ResourceManager.GetString("MainProductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational membership.
        /// </summary>
        public static string MembershipDescription {
            get {
                return ResourceManager.GetString("MembershipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social activities entry.
        /// </summary>
        public static string MembershipEntry {
            get {
                return ResourceManager.GetString("MembershipEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social activities &amp; memberships.
        /// </summary>
        public static string Memberships {
            get {
                return ResourceManager.GetString("Memberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition time to be able to start with new employer.
        /// </summary>
        public static string NoticePeriod {
            get {
                return ResourceManager.GetString("NoticePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice period.
        /// </summary>
        public static string NoticePeriodLabel {
            get {
                return ResourceManager.GetString("NoticePeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days.
        /// </summary>
        public static string NumberOfDays {
            get {
                return ResourceManager.GetString("NumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees.
        /// </summary>
        public static string NumberOfEmployess {
            get {
                return ResourceManager.GetString("NumberOfEmployess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry / business area.
        /// </summary>
        public static string OtherIndustry {
            get {
                return ResourceManager.GetString("OtherIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other contact information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other language.
        /// </summary>
        public static string OtherLanguageName {
            get {
                return ResourceManager.GetString("OtherLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent company name.
        /// </summary>
        public static string ParentCompanyName {
            get {
                return ResourceManager.GetString("ParentCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone *.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string PhoneCodePlaceholder {
            get {
                return ResourceManager.GetString("PhoneCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (mobile).
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name *.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy2 {
            get {
                return ResourceManager.GetString("Privacy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.amrop.lv/eng/privacy-policy.
        /// </summary>
        public static string PrivacyLink {
            get {
                return ResourceManager.GetString("PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project (if you are not part of existing assignment, please indicate desired position).
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for leaving (leave blank if you still work there).
        /// </summary>
        public static string ReasonForLeaving {
            get {
                return ResourceManager.GetString("ReasonForLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting to (name and position).
        /// </summary>
        public static string ReportingTo {
            get {
                return ResourceManager.GetString("ReportingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string RightsReserved {
            get {
                return ResourceManager.GetString("RightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary request (gross per month, currency).
        /// </summary>
        public static string SalaryRequest {
            get {
                return ResourceManager.GetString("SalaryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data was saved successfully!.
        /// </summary>
        public static string SaveNotice {
            get {
                return ResourceManager.GetString("SaveNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoken.
        /// </summary>
        public static string SpokenLevel {
            get {
                return ResourceManager.GetString("SpokenLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (YYYY) *.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (YYYY or MM.YYYY) *.
        /// </summary>
        public static string ToTimeWithMonth {
            get {
                return ResourceManager.GetString("ToTimeWithMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period to (YYYY).
        /// </summary>
        public static string ToYear {
            get {
                return ResourceManager.GetString("ToYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training company, trainer.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover (+currency, year).
        /// </summary>
        public static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 30 MEUR (2018).
        /// </summary>
        public static string TurnoverExample {
            get {
                return ResourceManager.GetString("TurnoverExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X EUR (YYYY).
        /// </summary>
        public static string TurnoverPlaceholder {
            get {
                return ResourceManager.GetString("TurnoverPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written.
        /// </summary>
        public static string WrittenLevel {
            get {
                return ResourceManager.GetString("WrittenLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
